"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class twist_t(object):

    __slots__ = ["linear", "angular", "timestamp"]

    __typenames__ = ["float", "float", "string"]

    __dimensions__ = [[3], [3], None]

    def __init__(self):
        self.linear = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.angular = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.timestamp = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(twist_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.linear[:3]))
        buf.write(struct.pack('>3f', *self.angular[:3]))
        __timestamp_encoded = self.timestamp.encode('utf-8')
        buf.write(struct.pack('>I', len(__timestamp_encoded)+1))
        buf.write(__timestamp_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != twist_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return twist_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = twist_t()
        self.linear = struct.unpack('>3f', buf.read(12))
        self.angular = struct.unpack('>3f', buf.read(12))
        __timestamp_len = struct.unpack('>I', buf.read(4))[0]
        self.timestamp = buf.read(__timestamp_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if twist_t in parents: return 0
        tmphash = (0x3900714a3ed0ea59) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if twist_t._packed_fingerprint is None:
            twist_t._packed_fingerprint = struct.pack(">Q", twist_t._get_hash_recursive([]))
        return twist_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", twist_t._get_packed_fingerprint())[0]

